# Generated by Django 5.0.3 on 2025-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('likelihood', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('mitigation', models.TextField()),
                ('status', models.CharField(default='Open', max_length=50)),
            ],
        ),
    ]
