# Generated by Django 5.0.3 on 2025-09-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_control_alter_risk_status_alter_risk_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='critical',
        ),
        migrations.RemoveField(
            model_name='control',
            name='status',
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Not Started', max_length=20),
        ),
    ]
