# Generated by Django 5.0.3 on 2025-10-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_created_at_asset_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bar',
            field=models.IntegerField(default=0),
        ),
    ]
