# Generated by Django 5.0.3 on 2025-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_title_control_name_remove_asset_critical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='critical',
            field=models.BooleanField(default=False),
        ),
    ]
