# Generated by Django 5.0.3 on 2025-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_critical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
