# Generated by Django 5.0.3 on 2025-09-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_asset_type_asset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Not Started', max_length=20),
        ),
    ]
