# Generated by Django 5.0.3 on 2025-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_control_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('framework', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Not Assessed', 'Not Assessed'), ('Partial', 'Partial'), ('Non Compliant', 'Non Compliant'), ('Compliant', 'Compliant'), ('Not Applicable', 'Not Applicable')], default='Not assessed', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('last_status', models.DateField(auto_now=True)),
            ],
        ),
    ]
