# Generated by Django 5.0.3 on 2025-09-18 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='description',
        ),
        migrations.RemoveField(
            model_name='control',
            name='name',
        ),
        migrations.RemoveField(
            model_name='control',
            name='status',
        ),
        migrations.AddField(
            model_name='control',
            name='controls_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='control',
            name='controls_deprecated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='control',
            name='controls_in_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='control',
            name='controls_missed_eta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='control',
            name='controls_on_hold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='control',
            name='controls_pending_p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='control',
            name='controls_todo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='control',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='total_controls',
            field=models.IntegerField(default=0),
        ),
    ]
