# Generated by Django 5.0.3 on 2025-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_control_description_remove_control_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='controls_active',
        ),
        migrations.RemoveField(
            model_name='control',
            name='controls_deprecated',
        ),
        migrations.RemoveField(
            model_name='control',
            name='controls_in_progress',
        ),
        migrations.RemoveField(
            model_name='control',
            name='controls_missed_eta',
        ),
        migrations.RemoveField(
            model_name='control',
            name='controls_on_hold',
        ),
        migrations.RemoveField(
            model_name='control',
            name='controls_pending_p1',
        ),
        migrations.RemoveField(
            model_name='control',
            name='controls_todo',
        ),
        migrations.RemoveField(
            model_name='control',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='control',
            name='total_controls',
        ),
        migrations.AddField(
            model_name='control',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='priority',
            field=models.CharField(blank=True, choices=[('P1', 'Priority 1'), ('P2', 'Priority 2'), ('P3', 'Priority 3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deprecated', 'Deprecated'), ('todo', 'To Do'), ('in progress', 'In Progress'), ('on hold', 'On Hold'), ('missed', 'Missed ETA')], default='todo', max_length=50),
        ),
    ]
