# Generated by Django 5.0.3 on 2025-09-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_control_controls_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='description',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='likelihood',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='mitigation',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='status',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='title',
        ),
        migrations.AddField(
            model_name='risk',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_assessments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_mapped_threats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_scenarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
