# Generated by Django 5.0.3 on 2025-09-21 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_risk_description_remove_risk_impact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
