# Generated by Django 5.0.3 on 2025-09-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_audit_created_at_audit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='not_assessed',
            field=models.BooleanField(default=False),
        ),
    ]
