# Generated by Django 5.0.3 on 2025-09-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_audit_not_assessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('Not Assessed', 'Not Assessed'), ('Partial', 'Partial'), ('Non Compliant', 'Non Compliant'), ('Compliant', 'Compliant'), ('Not Applicable', 'Not Applicable')], max_length=50),
        ),
    ]
