# Generated by Django 5.0.3 on 2025-09-25 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_domain_alter_audit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='perimeter',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('design', 'design'), ('development', 'development'), ('production', 'production'), ('End of life', 'End of life'), ('Dropped', 'Dropped')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_asigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_perimeter', to='core.asset')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perimeters', to='core.domain')),
            ],
        ),
    ]
