# Generated by Django 5.0.3 on 2025-09-27 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_perimeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('Not Assessed', 'Not Assessed'), ('Partial', 'Partial'), ('Non Compliant', 'Non Compliant'), ('Compliant', 'Compliant'), ('Not Applicable', 'Not Applicable')], default='Not Assessed', max_length=50),
        ),
        migrations.AlterField(
            model_name='perimeter',
            name='status',
            field=models.CharField(choices=[('design', 'design'), ('development', 'development'), ('production', 'production'), ('End of life', 'End of life'), ('Dropped', 'Dropped')], default='design', max_length=50),
        ),
    ]
