# Generated by Django 5.0.3 on 2025-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_domain_created_at_alter_audit_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Role', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='domain',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('Not Assessed', 'Not Assessed'), ('Partial', 'Partial'), ('Non Compliant', 'Non Compliant'), ('Compliant', 'Compliant'), ('Not Applicable', 'Not Applicable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perimeter',
            name='status',
            field=models.CharField(choices=[('design', 'design'), ('development', 'development'), ('production', 'production'), ('End of life', 'End of life'), ('Dropped', 'Dropped')], max_length=50),
        ),
    ]
