# Generated by Django 5.0.3 on 2025-09-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_remove_domain_created_at_alter_audit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(choices=[('Creater', 'Creater'), ('Reviewer', 'Reviewer'), ('Approver', 'Approver'), ('Admin', 'Admin')], default='Creator', max_length=100),
        ),
    ]
