# Generated by Django 5.0.3 on 2025-10-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perimeter',
            name='default_asigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_perimeter', to='core.user'),
        ),
    ]
