# Generated by Django 5.0.3 on 2025-10-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_perimeter_default_asigned'),
        ('core', '0018_usergroup_rename_email_user_email_and_more'),
    ]

    operations = [
    ]
